_target_: pytorch_lightning.callbacks.ModelCheckpoint

monitor: Acc/OA_val
mode: max
auto_insert_metric_name: False
filename: 'maxacc-{epoch}-LOSS={Loss/val:.5f}-REC={Losses/rec/val:.5f}-OA={Acc/OA_val:.2f}'